version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persist RabbitMQ data
      - rabbitmq_log:/var/log/rabbitmq # Persist RabbitMQ logs
    networks:
      - rabbitmq-web

volumes:
  rabbitmq_data:
  rabbitmq_log:

networks:
  rabbitmq-web: